version: '3'

services:

  python:
    build:
      context: .
      dockerfile: ./docker/python/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    tty: true
    stdin_open: true
